name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Pull Docker Image (Validation Step)
      - name: Pull Docker Image
        run: docker pull kishoresankarg/my-html-app

      # Step 4: SSH into EC2 and Deploy
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Removing old container if exists..."
            sudo docker rm -f myapp || true

            echo "Pulling latest Docker image..."
            sudo docker pull kishoresankarg/my-html-app

            echo "Starting new container..."
            sudo docker run -d \
              -p 80:80 \
              --restart always \
              --name myapp \
              kishoresankarg/my-html-app

            echo "Deployment completed successfully!"
